### ISSUE TITLE
[BUG] - Er kan niet meer door de pagina gescrolled worden wanneer de modal manual open/close via ESC gesloten wordt

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-modal#112]
**Omschrijf het probleem**
Wanneer je de modal manual open/close sluit door op ESC te drukken, kan je niet meer door de originele pagina scrollen. Eveneens bij de modal met veel tekst.

**Hoe te reproduceren**
Open de modal manual open/close en sluit deze via ESC.
Probeer te scrollen door de pagina.

**Gewenst gedrag**
Ik kan alsnog door de pagina scrollen.

**Comment by kevcraey** [comment]
cookie consent geimpacteerd: https://github.com/milieuinfo/webcomponent-vl-ui-cookie-consent/issues/3

**Comment by coemans** [comment]
Bug lijkt iets genuanceerder te zijn, in Firefox kan de modal die niet closable is toch gesloten worden via de ESC toets, dit mag niet mogelijk zijn en veroorzaakt vermoedelijk het probleem.
