### ISSUE TITLE
[BUG] - title van modal wordt niet getoond 

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-modal#140]
**Omschrijf het probleem**
Bij het openen van een vl-ui-modal wordt de title die in data-title staat niet getoond. Wel na het sluiten en heropenen van deze modal of na een page reload en heropenen van de modal.

**Hoe te reproduceren**
Modal met een title openen

Lokaal met `npm run dev` herstarten om telkens de bug terug te zien. 

**Gewenst gedrag**
Title van eerste keer zichtbaar maken

**Screenshots**
<img width="1680" alt="Screenshot 2020-07-07 at 14 00 18" src="https://user-images.githubusercontent.com/8820456/86781432-2c3ee680-c05e-11ea-8d44-b5fd372964a0.png">
<img width="1680" alt="Screenshot 2020-07-07 at 14 00 27" src="https://user-images.githubusercontent.com/8820456/86781447-2f39d700-c05e-11ea-939b-2ce60363a8d9.png">

**Omgeving (gelieve aan te vullen):**
 - Browser Chrome
 - Versie Version 83.0.4103.116 (Official Build) (64-bit)
 - Versie component 3.0.9

**Extra info**
Ook op ontwikkel getest en daar is hetzelfde probleem. Ik heb ook al geprobeerd om de data-title mee te geven aan de component, maar dat deed zelfs niets of ik deed misschien iets mis.

**Comment by coemans** [comment]
Op dit moment is het alleen mogelijk om met `data-vl-title` te werken. Je spreekt over `data-title` dus dat kan verklaren waarom de titel niet getoond wordt?

**Comment by coemans** [comment]
Het probleem kan op webcomponent niveau niet gereproduceerd worden, ticket wordt voorlopig afgesloten. Aarzel niet om ticket weer te openen als het probleem zich applicatief toch nog zou stellen.
