### ISSUE TITLE
[BUG] - Dialog-polyfill bug in combinatie met shadow DOM

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-modal#25]
**Omschrijf het probleem**
Voorlopig werd het probleem zelf opgelost in vl-ui-modal, maar dit veroorzaakt een manuele stap bij een upgrade van Webuniversum. Informeren bij dialog-polyfill om de fix door te voeren.

**Comment by coemans** [comment]
Er is ondertussen nieuwe release van [dialog-polyfill](https://github.com/GoogleChrome/dialog-polyfill/releases). Testen of deze release goed is, anders alsnog PR aanmaken.
