### ISSUE TITLE
[BUG] - Styling in action-group van modal staat nog niet goed

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-modal#26]
**Omschrijf het probleem**
De action-group heeft modal specifieke styling, die styling van de action-group in het geval van de modal moet toepassen. Deze is echter niet correct, zie afbeelding
<img width="656" alt="Schermafbeelding 2019-07-05 om 14 28 49" src="https://user-images.githubusercontent.com/1628243/64426613-4fe87780-d0af-11e9-8bca-ab1aa8cc6057.png">

**Comment by coemans** [comment]
Er kan best gebruik gemaakt worden van het button slot in combinatie met een annuleerbare variant zodat er geen nood is aan gebruik van de vl-action-group component. Een modal met meer dan 2 opties zijn we tot heden nog niet tegengekomen dus voorlopig wordt issue afgesloten.
