### ISSUE TITLE
[BUG] - Focus voor sluiten knop niet gelijk in Chrome en Fx

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-modal#56]
**Omschrijf het probleem**
Focus in Chrome is geen rechthoek maar wel in Firefox.

**Hoe te reproduceren**
Modal tonen met sluit knop

**Gewenst gedrag**
Gelijke weergave in Fx en Chrome

**Screenshots**
Firefox:
<img width="730" alt="fx" src="https://user-images.githubusercontent.com/29454303/66209686-363f4d80-e6b8-11e9-9fad-ae62041bd316.png">
Chrome
<img width="714" alt="chrome" src="https://user-images.githubusercontent.com/29454303/66209689-393a3e00-e6b8-11e9-9443-959d0a4dc949.png">

**Omgeving (gelieve aan te vullen):**
- Firefox: 70.0b10 (64-bit)
- Chrome: Version 77.0.3865.90 (Official Build) (64-bit)

**Extra info**
Ook het geval bij Webuniversum 3.9.2

**Comment by coemans** [comment]
Lijkt geen probleem meer te zijn bij de nieuwe huisstijl:

<img width="2560" alt="modal" src="https://user-images.githubusercontent.com/11139249/105735892-80df7b80-5f34-11eb-9ede-f3b97fe073ea.png">
